### ISSUE TITLE
Reason for difference in cite counts from get_citation_history and get_publications

### ISSUE THREAD

**Issue by patilv** [jkeirstead/scholar#16]
Is there a reason why the count of cites using the two methods should be different? Thanks.
id="B7vSqZsAAAAJ"
citationsbyyear=get_citation_history(id)
sum(citationsbyyear$cites)
pubs=get_publications(id)
sum(pubs$cites)

**Comment by jkeirstead** [comment]
This is because `get_publications` currently only returns the 20 most cited publications (in the same way that Google Scholar does natively).  If you want the two sums to match, you will have to download more publications.  This is implemented on the [develop](https://github.com/jkeirstead/scholar/tree/develop) branch; see also #13 and other closed issues.

**Comment by patilv** [comment]
Thanks
