### ISSUE TITLE
get_publications() to return day and month of publication

### ISSUE THREAD

**Issue by AngelCampos** [jkeirstead/scholar#79]
Could it be possible to have the date of publication (as in DD-MM-YYYY format or separate fields) added to the output of get_publications()? Or a function to extract this information from the pubid.

TIA

**Comment by jefferis** [comment]
I'm afraid this is not possible without following the link for each publication. This would be very expensive. 

For example if you start with [this profile](https://scholar.google.com/citations?user=1X-MOE8AAAAJ&hl=en&oi=ao), you would have to load the 308 linked pages for [each individual publication](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=1X-MOE8AAAAJ&citation_for_view=1X-MOE8AAAAJ:LkGwnXOMwfcC) in order to extract the `Publication date` field. This would be slow and would likely get you rate limited/blocked by google. Furthermore the style of the `Publication date` field is not consistent.
